# Generated by Django 5.1.3 on 2024-11-08 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.product')),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            bases=('sales.product',),
        ),
        migrations.CreateModel(
            name='DiscountedProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.product')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('sales.product',),
        ),
    ]
